version: '3.8'

services:
  app:
    build: .
    ports:
      - '3000:3000' # Mapeia a porta 3000 do contêiner para a porta 3000 do host
    volumes:
      - .:/usr/src/app # Sincroniza o diretório local com o contêiner
      - /usr/src/app/node_modules # Ignora a pasta node_modules local
    environment:
      - NODE_ENV=development
    depends_on:
      - db

  db:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_DATABASE: mydatabase
    ports:
      - '3306:3306'
    volumes:
      - mysql-data:/var/lib/mysql

volumes:
  mysql-data:
